name: Run Oksid Scraper

on:
  workflow_dispatch: # elle veya API'den tetiklenebilir

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd scripts/oksid
          pip install --no-cache-dir -r requirements.txt

      - name: Run Oksid scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          cd scripts/oksid
          python update_oksid.py
