name: Oksid Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/oksid/requirements.txt

      - name: Debug Supabase secrets
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL"
          echo "SUPABASE_KEY length: ${#SUPABASE_KEY}"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.oksid.update_oksid
